//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Controls/PlayerControll.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControll : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControll()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControll"",
    ""maps"": [
        {
            ""name"": ""PlayerKM"",
            ""id"": ""f0ab6f78-be26-4941-9f74-1805c57128d2"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""72db7106-c59d-41a0-8228-542de9466169"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""a49a7a30-13ce-4aa7-9aae-81ef3ba7875a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d4988b03-f71e-4cee-b956-53d77e84fa1f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08bf5a54-87a8-48a0-9910-61c0938aac4b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Hands"",
            ""id"": ""43f35142-91d4-4c19-b484-1b3408e8cd7f"",
            ""actions"": [
                {
                    ""name"": ""LeftHand"",
                    ""type"": ""Button"",
                    ""id"": ""c0715625-d965-44c4-bd8f-3c4a979f40f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHand"",
                    ""type"": ""Button"",
                    ""id"": ""ab768bc6-39b1-4b1d-bf51-825decfa3458"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""42061839-88bc-4823-9441-66904b652816"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bac9be6-57d0-4092-8006-15985b12beef"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player1"",
            ""id"": ""ec881914-5ce6-4952-a584-d9d2125c5454"",
            ""actions"": [
                {
                    ""name"": ""Move1"",
                    ""type"": ""Value"",
                    ""id"": ""b5dbed0a-45ed-4a13-b01a-8ab0ad046725"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump1"",
                    ""type"": ""Button"",
                    ""id"": ""364b8066-d3a6-49cd-a91f-6f7755d6d9d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabLeft1"",
                    ""type"": ""Button"",
                    ""id"": ""14edbc15-5be8-45d8-aa73-939ac67c075e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabRight1"",
                    ""type"": ""Button"",
                    ""id"": ""2665f1d7-8729-4f36-9580-d40f54327e0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a7793628-a17d-4cd6-a5bc-8de706cbc2ff"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""dd3e2c00-8913-4868-8757-79c09cdb039b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5db587f4-b27a-48bf-bc4a-c98c40ff0e05"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""12e9283e-7e19-472c-9148-b0903afe6458"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0a5ce15e-4ec6-45a2-bdd6-dd272b8fdd87"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ca18befe-5e7f-490c-b2f7-3140b8ab8e26"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f50efca8-5fe8-4199-8875-3755fab2db23"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabLeft1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03516b74-9ebd-48a7-bb8a-4d672eb4b1cd"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabRight1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player2"",
            ""id"": ""b8527dd3-002d-4712-95fa-bd3684176d2f"",
            ""actions"": [
                {
                    ""name"": ""Move2"",
                    ""type"": ""Value"",
                    ""id"": ""8be7a7a1-091d-447b-9170-46b8df0b4080"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump2"",
                    ""type"": ""Button"",
                    ""id"": ""3f4eba1f-9121-4a13-ac19-7f03db321443"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabLeft2"",
                    ""type"": ""Button"",
                    ""id"": ""70065b62-067a-4572-ba90-2d8454c088a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabRight2"",
                    ""type"": ""Button"",
                    ""id"": ""227ed391-568e-498e-86c4-ff327904c5cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c01726b5-d403-4f25-8243-e4a6bd26dc73"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""af1e39b3-963c-4aa3-bf92-abd1d5bbc1c3"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5c151a71-d4d7-4bdd-9498-d9db28e5a081"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9d26d0aa-e1ec-463f-bbe2-fd8d24611e4f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""93dc975a-ca8a-431b-ab32-e87483c48c2a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1a4ef59d-f4ce-4d15-83d6-65a9e3850d7e"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2693248a-5c8d-4f44-b226-355b4f473e4b"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabLeft2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4491f56a-2b1d-411a-8d02-5da31e8d49a5"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabRight2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player3xsx"",
            ""id"": ""d79cddfb-fcd2-47de-932a-fbb8092cab36"",
            ""actions"": [
                {
                    ""name"": ""Move3"",
                    ""type"": ""Value"",
                    ""id"": ""3bca5e2f-bd42-49f2-9ce4-556c73169a94"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump3"",
                    ""type"": ""Button"",
                    ""id"": ""b8946777-c852-42dd-9328-12fd99c6d683"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabLeft3"",
                    ""type"": ""Button"",
                    ""id"": ""58703fdd-82a7-47a7-8ce9-ac0b9d2927cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabRight3"",
                    ""type"": ""Button"",
                    ""id"": ""9191f2e2-a330-41a7-83fa-205825dbb035"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8e8d76bd-d3ed-4e6e-91b7-49460604e8be"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d3a3b9a-3296-47bf-8f9d-b7619753c8c1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5129598d-e596-4d44-8376-074bde28de46"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabLeft3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99a6b66f-fa8b-48bb-bf47-f88fd001cd2f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabRight3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player4xsx"",
            ""id"": ""324c5d6b-92f9-4433-9ce4-78b4b817e1d0"",
            ""actions"": [
                {
                    ""name"": ""Move4"",
                    ""type"": ""Value"",
                    ""id"": ""b5c92cbe-eb06-49c5-ad1f-1f66d174d985"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump4"",
                    ""type"": ""Button"",
                    ""id"": ""6acce5df-7e77-4a43-a5f6-76fa67db7d5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabLeft4"",
                    ""type"": ""Button"",
                    ""id"": ""9b5513b9-1dfc-4e96-b9dc-22523c5cbb40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabRight4"",
                    ""type"": ""Button"",
                    ""id"": ""1601f1bd-68cc-4e13-984a-b7dac2a90bb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""797d4e0f-5a9d-4205-8251-091117c62c0c"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""318c280e-b562-4d64-89e9-9501a5b92c1b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa991a26-3689-41c2-a1ce-5dc1ddaf1366"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabLeft4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cac81032-97f1-468b-8ea8-56748d95032c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabRight4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerKM
        m_PlayerKM = asset.FindActionMap("PlayerKM", throwIfNotFound: true);
        m_PlayerKM_Move = m_PlayerKM.FindAction("Move", throwIfNotFound: true);
        m_PlayerKM_Jump = m_PlayerKM.FindAction("Jump", throwIfNotFound: true);
        // Hands
        m_Hands = asset.FindActionMap("Hands", throwIfNotFound: true);
        m_Hands_LeftHand = m_Hands.FindAction("LeftHand", throwIfNotFound: true);
        m_Hands_RightHand = m_Hands.FindAction("RightHand", throwIfNotFound: true);
        // Player1
        m_Player1 = asset.FindActionMap("Player1", throwIfNotFound: true);
        m_Player1_Move1 = m_Player1.FindAction("Move1", throwIfNotFound: true);
        m_Player1_Jump1 = m_Player1.FindAction("Jump1", throwIfNotFound: true);
        m_Player1_GrabLeft1 = m_Player1.FindAction("GrabLeft1", throwIfNotFound: true);
        m_Player1_GrabRight1 = m_Player1.FindAction("GrabRight1", throwIfNotFound: true);
        // Player2
        m_Player2 = asset.FindActionMap("Player2", throwIfNotFound: true);
        m_Player2_Move2 = m_Player2.FindAction("Move2", throwIfNotFound: true);
        m_Player2_Jump2 = m_Player2.FindAction("Jump2", throwIfNotFound: true);
        m_Player2_GrabLeft2 = m_Player2.FindAction("GrabLeft2", throwIfNotFound: true);
        m_Player2_GrabRight2 = m_Player2.FindAction("GrabRight2", throwIfNotFound: true);
        // Player3xsx
        m_Player3xsx = asset.FindActionMap("Player3xsx", throwIfNotFound: true);
        m_Player3xsx_Move3 = m_Player3xsx.FindAction("Move3", throwIfNotFound: true);
        m_Player3xsx_Jump3 = m_Player3xsx.FindAction("Jump3", throwIfNotFound: true);
        m_Player3xsx_GrabLeft3 = m_Player3xsx.FindAction("GrabLeft3", throwIfNotFound: true);
        m_Player3xsx_GrabRight3 = m_Player3xsx.FindAction("GrabRight3", throwIfNotFound: true);
        // Player4xsx
        m_Player4xsx = asset.FindActionMap("Player4xsx", throwIfNotFound: true);
        m_Player4xsx_Move4 = m_Player4xsx.FindAction("Move4", throwIfNotFound: true);
        m_Player4xsx_Jump4 = m_Player4xsx.FindAction("Jump4", throwIfNotFound: true);
        m_Player4xsx_GrabLeft4 = m_Player4xsx.FindAction("GrabLeft4", throwIfNotFound: true);
        m_Player4xsx_GrabRight4 = m_Player4xsx.FindAction("GrabRight4", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerKM
    private readonly InputActionMap m_PlayerKM;
    private IPlayerKMActions m_PlayerKMActionsCallbackInterface;
    private readonly InputAction m_PlayerKM_Move;
    private readonly InputAction m_PlayerKM_Jump;
    public struct PlayerKMActions
    {
        private @PlayerControll m_Wrapper;
        public PlayerKMActions(@PlayerControll wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerKM_Move;
        public InputAction @Jump => m_Wrapper.m_PlayerKM_Jump;
        public InputActionMap Get() { return m_Wrapper.m_PlayerKM; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerKMActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerKMActions instance)
        {
            if (m_Wrapper.m_PlayerKMActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerKMActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerKMActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerKMActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_PlayerKMActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerKMActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerKMActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_PlayerKMActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public PlayerKMActions @PlayerKM => new PlayerKMActions(this);

    // Hands
    private readonly InputActionMap m_Hands;
    private IHandsActions m_HandsActionsCallbackInterface;
    private readonly InputAction m_Hands_LeftHand;
    private readonly InputAction m_Hands_RightHand;
    public struct HandsActions
    {
        private @PlayerControll m_Wrapper;
        public HandsActions(@PlayerControll wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftHand => m_Wrapper.m_Hands_LeftHand;
        public InputAction @RightHand => m_Wrapper.m_Hands_RightHand;
        public InputActionMap Get() { return m_Wrapper.m_Hands; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HandsActions set) { return set.Get(); }
        public void SetCallbacks(IHandsActions instance)
        {
            if (m_Wrapper.m_HandsActionsCallbackInterface != null)
            {
                @LeftHand.started -= m_Wrapper.m_HandsActionsCallbackInterface.OnLeftHand;
                @LeftHand.performed -= m_Wrapper.m_HandsActionsCallbackInterface.OnLeftHand;
                @LeftHand.canceled -= m_Wrapper.m_HandsActionsCallbackInterface.OnLeftHand;
                @RightHand.started -= m_Wrapper.m_HandsActionsCallbackInterface.OnRightHand;
                @RightHand.performed -= m_Wrapper.m_HandsActionsCallbackInterface.OnRightHand;
                @RightHand.canceled -= m_Wrapper.m_HandsActionsCallbackInterface.OnRightHand;
            }
            m_Wrapper.m_HandsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LeftHand.started += instance.OnLeftHand;
                @LeftHand.performed += instance.OnLeftHand;
                @LeftHand.canceled += instance.OnLeftHand;
                @RightHand.started += instance.OnRightHand;
                @RightHand.performed += instance.OnRightHand;
                @RightHand.canceled += instance.OnRightHand;
            }
        }
    }
    public HandsActions @Hands => new HandsActions(this);

    // Player1
    private readonly InputActionMap m_Player1;
    private IPlayer1Actions m_Player1ActionsCallbackInterface;
    private readonly InputAction m_Player1_Move1;
    private readonly InputAction m_Player1_Jump1;
    private readonly InputAction m_Player1_GrabLeft1;
    private readonly InputAction m_Player1_GrabRight1;
    public struct Player1Actions
    {
        private @PlayerControll m_Wrapper;
        public Player1Actions(@PlayerControll wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move1 => m_Wrapper.m_Player1_Move1;
        public InputAction @Jump1 => m_Wrapper.m_Player1_Jump1;
        public InputAction @GrabLeft1 => m_Wrapper.m_Player1_GrabLeft1;
        public InputAction @GrabRight1 => m_Wrapper.m_Player1_GrabRight1;
        public InputActionMap Get() { return m_Wrapper.m_Player1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player1Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer1Actions instance)
        {
            if (m_Wrapper.m_Player1ActionsCallbackInterface != null)
            {
                @Move1.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove1;
                @Move1.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove1;
                @Move1.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove1;
                @Jump1.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnJump1;
                @Jump1.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnJump1;
                @Jump1.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnJump1;
                @GrabLeft1.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabLeft1;
                @GrabLeft1.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabLeft1;
                @GrabLeft1.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabLeft1;
                @GrabRight1.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabRight1;
                @GrabRight1.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabRight1;
                @GrabRight1.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabRight1;
            }
            m_Wrapper.m_Player1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move1.started += instance.OnMove1;
                @Move1.performed += instance.OnMove1;
                @Move1.canceled += instance.OnMove1;
                @Jump1.started += instance.OnJump1;
                @Jump1.performed += instance.OnJump1;
                @Jump1.canceled += instance.OnJump1;
                @GrabLeft1.started += instance.OnGrabLeft1;
                @GrabLeft1.performed += instance.OnGrabLeft1;
                @GrabLeft1.canceled += instance.OnGrabLeft1;
                @GrabRight1.started += instance.OnGrabRight1;
                @GrabRight1.performed += instance.OnGrabRight1;
                @GrabRight1.canceled += instance.OnGrabRight1;
            }
        }
    }
    public Player1Actions @Player1 => new Player1Actions(this);

    // Player2
    private readonly InputActionMap m_Player2;
    private IPlayer2Actions m_Player2ActionsCallbackInterface;
    private readonly InputAction m_Player2_Move2;
    private readonly InputAction m_Player2_Jump2;
    private readonly InputAction m_Player2_GrabLeft2;
    private readonly InputAction m_Player2_GrabRight2;
    public struct Player2Actions
    {
        private @PlayerControll m_Wrapper;
        public Player2Actions(@PlayerControll wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move2 => m_Wrapper.m_Player2_Move2;
        public InputAction @Jump2 => m_Wrapper.m_Player2_Jump2;
        public InputAction @GrabLeft2 => m_Wrapper.m_Player2_GrabLeft2;
        public InputAction @GrabRight2 => m_Wrapper.m_Player2_GrabRight2;
        public InputActionMap Get() { return m_Wrapper.m_Player2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player2Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer2Actions instance)
        {
            if (m_Wrapper.m_Player2ActionsCallbackInterface != null)
            {
                @Move2.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnMove2;
                @Move2.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnMove2;
                @Move2.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnMove2;
                @Jump2.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump2;
                @Jump2.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump2;
                @Jump2.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump2;
                @GrabLeft2.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrabLeft2;
                @GrabLeft2.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrabLeft2;
                @GrabLeft2.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrabLeft2;
                @GrabRight2.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrabRight2;
                @GrabRight2.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrabRight2;
                @GrabRight2.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrabRight2;
            }
            m_Wrapper.m_Player2ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move2.started += instance.OnMove2;
                @Move2.performed += instance.OnMove2;
                @Move2.canceled += instance.OnMove2;
                @Jump2.started += instance.OnJump2;
                @Jump2.performed += instance.OnJump2;
                @Jump2.canceled += instance.OnJump2;
                @GrabLeft2.started += instance.OnGrabLeft2;
                @GrabLeft2.performed += instance.OnGrabLeft2;
                @GrabLeft2.canceled += instance.OnGrabLeft2;
                @GrabRight2.started += instance.OnGrabRight2;
                @GrabRight2.performed += instance.OnGrabRight2;
                @GrabRight2.canceled += instance.OnGrabRight2;
            }
        }
    }
    public Player2Actions @Player2 => new Player2Actions(this);

    // Player3xsx
    private readonly InputActionMap m_Player3xsx;
    private IPlayer3xsxActions m_Player3xsxActionsCallbackInterface;
    private readonly InputAction m_Player3xsx_Move3;
    private readonly InputAction m_Player3xsx_Jump3;
    private readonly InputAction m_Player3xsx_GrabLeft3;
    private readonly InputAction m_Player3xsx_GrabRight3;
    public struct Player3xsxActions
    {
        private @PlayerControll m_Wrapper;
        public Player3xsxActions(@PlayerControll wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move3 => m_Wrapper.m_Player3xsx_Move3;
        public InputAction @Jump3 => m_Wrapper.m_Player3xsx_Jump3;
        public InputAction @GrabLeft3 => m_Wrapper.m_Player3xsx_GrabLeft3;
        public InputAction @GrabRight3 => m_Wrapper.m_Player3xsx_GrabRight3;
        public InputActionMap Get() { return m_Wrapper.m_Player3xsx; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player3xsxActions set) { return set.Get(); }
        public void SetCallbacks(IPlayer3xsxActions instance)
        {
            if (m_Wrapper.m_Player3xsxActionsCallbackInterface != null)
            {
                @Move3.started -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnMove3;
                @Move3.performed -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnMove3;
                @Move3.canceled -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnMove3;
                @Jump3.started -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnJump3;
                @Jump3.performed -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnJump3;
                @Jump3.canceled -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnJump3;
                @GrabLeft3.started -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnGrabLeft3;
                @GrabLeft3.performed -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnGrabLeft3;
                @GrabLeft3.canceled -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnGrabLeft3;
                @GrabRight3.started -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnGrabRight3;
                @GrabRight3.performed -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnGrabRight3;
                @GrabRight3.canceled -= m_Wrapper.m_Player3xsxActionsCallbackInterface.OnGrabRight3;
            }
            m_Wrapper.m_Player3xsxActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move3.started += instance.OnMove3;
                @Move3.performed += instance.OnMove3;
                @Move3.canceled += instance.OnMove3;
                @Jump3.started += instance.OnJump3;
                @Jump3.performed += instance.OnJump3;
                @Jump3.canceled += instance.OnJump3;
                @GrabLeft3.started += instance.OnGrabLeft3;
                @GrabLeft3.performed += instance.OnGrabLeft3;
                @GrabLeft3.canceled += instance.OnGrabLeft3;
                @GrabRight3.started += instance.OnGrabRight3;
                @GrabRight3.performed += instance.OnGrabRight3;
                @GrabRight3.canceled += instance.OnGrabRight3;
            }
        }
    }
    public Player3xsxActions @Player3xsx => new Player3xsxActions(this);

    // Player4xsx
    private readonly InputActionMap m_Player4xsx;
    private IPlayer4xsxActions m_Player4xsxActionsCallbackInterface;
    private readonly InputAction m_Player4xsx_Move4;
    private readonly InputAction m_Player4xsx_Jump4;
    private readonly InputAction m_Player4xsx_GrabLeft4;
    private readonly InputAction m_Player4xsx_GrabRight4;
    public struct Player4xsxActions
    {
        private @PlayerControll m_Wrapper;
        public Player4xsxActions(@PlayerControll wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move4 => m_Wrapper.m_Player4xsx_Move4;
        public InputAction @Jump4 => m_Wrapper.m_Player4xsx_Jump4;
        public InputAction @GrabLeft4 => m_Wrapper.m_Player4xsx_GrabLeft4;
        public InputAction @GrabRight4 => m_Wrapper.m_Player4xsx_GrabRight4;
        public InputActionMap Get() { return m_Wrapper.m_Player4xsx; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player4xsxActions set) { return set.Get(); }
        public void SetCallbacks(IPlayer4xsxActions instance)
        {
            if (m_Wrapper.m_Player4xsxActionsCallbackInterface != null)
            {
                @Move4.started -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnMove4;
                @Move4.performed -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnMove4;
                @Move4.canceled -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnMove4;
                @Jump4.started -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnJump4;
                @Jump4.performed -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnJump4;
                @Jump4.canceled -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnJump4;
                @GrabLeft4.started -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnGrabLeft4;
                @GrabLeft4.performed -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnGrabLeft4;
                @GrabLeft4.canceled -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnGrabLeft4;
                @GrabRight4.started -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnGrabRight4;
                @GrabRight4.performed -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnGrabRight4;
                @GrabRight4.canceled -= m_Wrapper.m_Player4xsxActionsCallbackInterface.OnGrabRight4;
            }
            m_Wrapper.m_Player4xsxActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move4.started += instance.OnMove4;
                @Move4.performed += instance.OnMove4;
                @Move4.canceled += instance.OnMove4;
                @Jump4.started += instance.OnJump4;
                @Jump4.performed += instance.OnJump4;
                @Jump4.canceled += instance.OnJump4;
                @GrabLeft4.started += instance.OnGrabLeft4;
                @GrabLeft4.performed += instance.OnGrabLeft4;
                @GrabLeft4.canceled += instance.OnGrabLeft4;
                @GrabRight4.started += instance.OnGrabRight4;
                @GrabRight4.performed += instance.OnGrabRight4;
                @GrabRight4.canceled += instance.OnGrabRight4;
            }
        }
    }
    public Player4xsxActions @Player4xsx => new Player4xsxActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IPlayerKMActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
    }
    public interface IHandsActions
    {
        void OnLeftHand(InputAction.CallbackContext context);
        void OnRightHand(InputAction.CallbackContext context);
    }
    public interface IPlayer1Actions
    {
        void OnMove1(InputAction.CallbackContext context);
        void OnJump1(InputAction.CallbackContext context);
        void OnGrabLeft1(InputAction.CallbackContext context);
        void OnGrabRight1(InputAction.CallbackContext context);
    }
    public interface IPlayer2Actions
    {
        void OnMove2(InputAction.CallbackContext context);
        void OnJump2(InputAction.CallbackContext context);
        void OnGrabLeft2(InputAction.CallbackContext context);
        void OnGrabRight2(InputAction.CallbackContext context);
    }
    public interface IPlayer3xsxActions
    {
        void OnMove3(InputAction.CallbackContext context);
        void OnJump3(InputAction.CallbackContext context);
        void OnGrabLeft3(InputAction.CallbackContext context);
        void OnGrabRight3(InputAction.CallbackContext context);
    }
    public interface IPlayer4xsxActions
    {
        void OnMove4(InputAction.CallbackContext context);
        void OnJump4(InputAction.CallbackContext context);
        void OnGrabLeft4(InputAction.CallbackContext context);
        void OnGrabRight4(InputAction.CallbackContext context);
    }
}
